### PR TITLE
dev-v0.2.0 - Update API documentation according to v0.2.0 API definition

### PR DESCRIPTION
**Pull request by jpengar**
This PR addresses issue https://github.com/camaraproject/HomeDevicesQoD/issues/18

It will include [v0.1.0 API documentation](https://github.com/camaraproject/HomeDevicesQoD/tree/main/documentation/API_documentation) required updates to be aligned with v0.2.0 API version definition.

So far:
- PR https://github.com/camaraproject/HomeDevicesQoD/pull/13
- PR https://github.com/camaraproject/HomeDevicesQoD/pull/14

### CODE REVIEW

**Review by bigludo7 — APPROVED** [review]
Looks good for me.

**Review by rartych — APPROVED** [review]

**Review by monamok — APPROVED** [review]
LGTM

**Comment by jpengar** [comment]
Doc changes related to issue https://github.com/camaraproject/HomeDevicesQoD/issues/23 and PR https://github.com/camaraproject/HomeDevicesQoD/pull/25 will be included in this PR.

**Comment by jpengar** [comment]
This PR is going to be MERGED to `dev-v0.2.0` branch with current documentation status (i.e. NOT including Doc changes related to issue https://github.com/camaraproject/HomeDevicesQoD/issues/23 and PR https://github.com/camaraproject/HomeDevicesQoD/pull/25). 

This is part of the process described in the https://github.com/camaraproject/HomeDevicesQoD/issues/27 issue to adapt the project to the release/versioning policy agreed in Commonalities, i.e. the `main` branch is assumed to be the latest. Documentation work corresponding to API release v0.2.0 (when resumed) will be done against the `main' branch until release v0.2.0 is agreed to be closed.

**Pull request merged**
